# PATHS

path: /home/pranav/Projects/Final_AUV/shark_sawfish/bbox_backup/data
train: images/train      
val: images/val        
test: images/test        

# CLASSES
nc: 2
names:
  0: shark
  1: sawfish